export const consentList = {
    EC: [
        'Agreement of Confidentiality',
        'Consent for Emergency Medical Treatment',
        'Consent for Routine Medical Treatment',
        'Fish Oil',
        'Guardian Conditions of Admission',
        'Guardian General Release and Agreement',
        'Influenza Consent',
        'Intake Admitting Orders',
        'Lab Disclosure',
        'Non-Approved Call List',
        'Respiratory Testing Consent',
        'PRN Consent',
        'Telehealth Consent',
        'Age Waiver',
        'Agency Oversight and Client Rights',
        'Mandatory Reporting Requirements',
        'Omnicare Pharmacy Enrollment',
        'Pharmacy Consent Form',
        'Physician Licensure Acknowledgement',
        'Consent for Tutorial Services',
        'Grievance Procedures',
        'Skate Park Consent'
    ],
    ROI: [
        'Guardian',
        'Parent',
        'Current Therapist',
        'Insurance',
        'Other Treatment Program',
        'Pharmacy',
        'Psychiatrist',
        'Referent',
        'School District',
        'School',
        'CHOC Hospital',
        'PDQ Urgent Care',
        'Additional Contact',
        'Primary Care Physician',

    ]
}